### ISSUE TITLE
Missing README.md 😭

### ISSUE THREAD

**Issue by LiCern** [fac20/WEEK3-ABEH-ToDoList#20]

**Comment by jamesj-0** [comment]
Please make sure you are writing documentation! Its the best habit you can get into as a programmer, It shouldn't be a last minute thought 😥 

If you're stuck with what to put, theres a really badass guide to help you out! 
https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3
